### ISSUE TITLE
您好，请问 使用这个 client 去连接的 websocket Server有版本要求吗？

### ISSUE THREAD

**Issue by saisaixv** [0xZhangKe/WebSocketDemo#15]
我用go 写的websocket server，使用 go的websocket client 可以连上，但是用这个demo 连接不上

11-23 11:30:09.660 15225-16396/com.zhangke.websocketdemo I/WebSocketLib: 正在重连，请勿重复调用。
11-23 11:30:09.662 15225-16397/com.zhangke.websocketdemo I/qtaguid: Untagging socket 80 failed errno=-22
11-23 11:30:10.162 15225-16398/com.zhangke.websocketdemo I/WebSocketLib: 正在重连，请勿重复调用。
11-23 11:30:10.163 15225-16399/com.zhangke.websocketdemo I/qtaguid: Untagging socket 80 failed errno=-22
11-23 11:30:10.660 15225-16400/com.zhangke.websocketdemo I/WebSocketLib: 正在重连，请勿重复调用。
11-23 11:30:10.661 15225-16401/com.zhangke.websocketdemo I/qtaguid: Untagging socket 80 failed errno=-22
11-23 11:30:11.168 15225-16402/com.zhangke.websocketdemo I/WebSocketLib: 正在重连，请勿重复调用。
11-23 11:30:11.169 15225-16403/com.zhangke.websocketdemo I/qtaguid: Untagging socket 80 failed errno=-22

**Comment by 0xZhangKe** [comment]
没有要求，应该是其他原因导致的无法连接。
