### ISSUE TITLE
运行lib库报错

### ISSUE THREAD

**Issue by flynihao53** [0xZhangKe/WebSocketDemo#2]
![default](https://user-images.githubusercontent.com/19507653/41705205-e6dd04ae-756a-11e8-8248-f43dd8ca20ac.png)
，这个怎么破？

**Comment by 0xZhangKe** [comment]
https://github.com/0xZhangKe/WebSocketDemo/blob/master/build.gradle#22
看下22行，需要添加一个 maven 仓库

**Comment by flynihao53** [comment]
多谢，我试试
