### ISSUE TITLE
接受消息的地方，直接用eventbus发出去行吗？

### ISSUE THREAD

**Issue by KevinLium** [0xZhangKe/WebSocketDemo#20]
非常感谢大佬的源码贡献！！！
拜读了一下代码，感觉思路清晰，德芙般丝滑。。
但是
有个想法，就是在收到消息的地方，直接发送eventbus可以吗？然后处理eventbus的地方 都放在baseActivity里面。发消息也是丢给服务去做。
你肯定想到了这么做，既然没有选择这个方案，肯定有坑，能告知一二吗？

**Comment by 0xZhangKe** [comment]
@KevinLium 可以这么做，但这么做我就得依赖一个第三方的框架，对使用者不友好，但你不用考虑这个问题，可以直接用。

**Comment by 0xZhangKe** [comment]
@KevinLium 我也没做过。
