### ISSUE TITLE
接收Base64图片数据问题

### ISSUE THREAD

**Issue by lichao3140** [0xZhangKe/WebSocketDemo#23]
框架能够正常接收图片base64数据，现在存在一个问题，启动应用第一次接收图片数据webSocket会断开然后重连，接收不到数据，得退出应用重启才能接收到，请问这是什么原因？

**Comment by 0xZhangKe** [comment]
@lichao3140 接受完自动断开？可能因为数据量太大了吧。

**Comment by Alexxiaopang** [comment]
数据量太大，超过500k就会出现这个，我也在找为什么会这样
