### ISSUE TITLE
没有调用连接方法，自动连接了

### ISSUE THREAD

**Issue by qssq** [0xZhangKe/WebSocketDemo#27]
我发现回调收到了连接成功的回调。

**Comment by qssq** [comment]
不填写地址就没事

**Comment by 0xZhangKe** [comment]
哪个版本，及重现步骤。

**Comment by qssq** [comment]
3.0.1 
就初始化一些配置，没有调用start, connect方法，这没毛病吧，为什么会连接呢，不填写地址也会连接，但是是连接失败。

**Comment by 0xZhangKe** [comment]
调用 init 方法初始化时会自动连接。
