### ISSUE TITLE
如题提供泛型解析数据呢？

### ISSUE THREAD

**Issue by luotext** [0xZhangKe/WebSocketDemo#35]
就是我这边返回的数据是带42["aaa",{"data":[{"bbb":"luo","ccc":"ddd"},{...}]这样的返回数据，怎么把前面的42给去掉，再将泛型应用上呢？onMessage(String message, T data)。

**Comment by 0xZhangKe** [comment]
处理一下这个字符串然后转换成对应的实体 将其作为第二个参数传入 onMessage 方法既可
