### ISSUE TITLE
错误: 找不到符号 符号:   方法 reconnect() 位置: 类型为WebSocketServiceConnectManager的变量 mConnectManager

### ISSUE THREAD

**Issue by feng612266** [0xZhangKe/WebSocketDemo#4]
AbsWebSocketActivity、AbsWebSocketFragment中 
@Override
    public void reconnect() {
        mConnectManager.reconnect();
    }
是否要写成 @Override
    public void reconnect() {
        mConnectManager.mWebSocketService.reconnect();
    }
还是直接注释掉

**Comment by 0xZhangKe** [comment]
@feng612266 抱歉，刚刚推送了 2.2 版本已经解决了这个问题，更新一下即可。
WebSocket 相关的方法应该都放在 WebSocketServiceConnectManager 中，所以在这个里面加了一个 reconnect 公开方法。
感谢提醒。
