### ISSUE TITLE
重要bug！！！接收消息异步导致消息乱序！

### ISSUE THREAD

**Issue by bannerkun** [0xZhangKe/WebSocketDemo#44]
使用这个框架后接收到的离线消息id都是乱序，所以追求消息同步处理的朋友，不能使用这个库了哦，我已经换成okhttp自带的websocket框架解决了！！！

**Comment by 0xZhangKe** [comment]
@bannerkun 消息 id？这是你们自己定义的东西吧，跟我的库有什么关系？？？

**Comment by bannerkun** [comment]
这个库处理消息是使用异步方式，导致乱序，想要的结果不正确

**Comment by 0xZhangKe** [comment]
@bannerkun WebSocket 本来就是异步。

**Comment by gsn516** [comment]
同步消息自己加个锁啊。。。，真问题问的真的是
  /**
     * 发送同步請求
     *
     * @param notice
     * @param msgid
     * @return
     */
    public Object sendsyc(String notice, String msgid) {
        if (TextUtils.isEmpty(notice)) {
            return null;
        }
        Request<String> request = RequestFactory.createStringRequest();
        request.setRequestData(notice);
        return sendRequestsyn(request, msgid);
    }
 /**
     * 发送数据
     */
    private Object sendRequestsyn(Request request, String msgid) {
        if (destroyed) {
            return null;
        }
        if (msgid != null) {
            LockObj lockobj = new LockObj();
            lockobj.setMsgid(msgid);
            locks.put(lockobj.getMsgid(), lockobj);
            synchronized (lockobj) {
                mWebSocketEngine.sendRequest(mWebSocket, request, mSocketWrapperListener);
...............
