### ISSUE TITLE
本地测试的时候连接不成功

### ISSUE THREAD

**Issue by Tomas-YI** [0xZhangKe/WebSocketDemo#60]
本地生成一个ServerSocket然后模拟器上运行客户端连不上，setting.setConnectUrl("wss://192.168.0.254:55556");
java.net.URISyntaxException: Illegal character in path at index 4: your connect url
        at libcore.net.UriCodec.validate(UriCodec.java:63)

**Comment by 0xZhangKe** [comment]
@michaelyiwei 看报错信息，应该是你的 url 字符不对
