### ISSUE TITLE
如何自定义Ping包的内容

### ISSUE THREAD

**Issue by jinbolx** [0xZhangKe/WebSocketDemo#61]
客户端和服务端心跳检查时需要发送自定义ping包，请问如何实现？直接自定义一个定时器，然后send("ping msg") 就可以吗

**Comment by 0xZhangKe** [comment]
@jinbolx 看文档，可以自定义 frame，void sendFrame(Framedata framedata);

**Comment by 442048209as** [comment]
@jinbolx 请问这个解决了吗？自定义ping包的，是自己写定时器，调用sendFrame方法吗？

**Comment by jinbolx** [comment]
> @jinbolx 请问这个解决了吗？自定义ping包的，是自己写定时器，调用sendFrame方法吗？

是的
